// GIVEN A POINT (X, Y) WRITE A PROG T0 FIND OUT IF IT LIES IN THE 
// 1ST QUADRANT, 2ND QUARANT, 3RD QUADRANT, 4TH QUADRANT ON THE X-AXIS, Y-AXIS OR AT THE ORIGIN VIZ(0, 0)

#include <stdio.h>
int main(){

    return 0;
}